name: ddsp-pytorch

channels:
- pytorch
- defaults
- conda-forge

dependencies:
- python=3.8
- cudatoolkit=11.0
- cudnn
- pytorch
- torchvision
- torchaudio
- omegaconf
- tqdm
- tensorboardX
- pip
- pip:
  - python-osc
  - streamlit
  - JACK-Client
